mozilla/addons

docs/server/push-duty.rst
This helps me (and others):
* see at a glance who is responsible for the push right from their IRC clients
* clear out my add-ons tagging/pushing meetings this week if it's not me
=> Instruct push hero to change IRC topic

docs/server/push-duty.rst
Pushing a single tag is preferable and I've also added a note about alternate remote configuration and suffixing tags when new tags are created with further cherry-picks.
=> Document pushing a single tag

README.md, docs/repositories.rst
See http://blog.readthedocs.com/securing-subdomains/ for more details.
=> Update our links to use readthedocs.io.

docs/server/push-duty.rst, docs/ux/disco-pane.rst
We need to land https://github.com/mozilla/addons-frontend/pull/505/files for that command to work. Hoping to automate this at some point but not yet.
=> Document tagging addons-frontend

docs/server/push-duty.rst
Just noticed this while reading the push docs.
=> Fix error in push duty README

CODE_OF_CONDUCT.md
The link was not correctly displayed because there was a space between the [title] (http://and/the/url)
=> Fixed CoC link syntax

docs/server/push-duty.rst
As per the discussion in IRC, it probably makes sense to add this to our docs.
=> Indicate the customary time that code is frozen and tagged

docs/server/push-duty.rst
Would it make sense to add this link in the list of version links to check?
=> Add link to __frontend_version__ on -stage

releases/2017/05/11.md, releases/2017/05/18.md, releases/2017/05/25.md, releases/2017/06/22.md, releases/2017/07/27.md, releases/2017/08/03.md, releases/2017/08/10.md, releases/2017/08/17.md
This updates historical deployment links to point to the current app instead of the deprecated one.
=> Update links from old app to new addons-pm app

docs/server/push-duty.rst
Update push duty docs to indicate that part of the duties includes doing l10n extraction
=> Indicate that part of push duty is to do the l10n extraction

docs/conf.py
Failed link checks to bugzilla buglists turned out to be a bug that has been identified and fixed: https://bugzilla.mozilla.org/show_bug.cgi?id=1668299
=> Remove bugzilla from linkcheck ignore list

.github/stale.yml
Removes the contrib:welcome label from stalebot exclusions.
=> Remove contrib:welcome from stalebot config

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/task-addons-frontend.yml, .github/ISSUE_TEMPLATE/task-addons-server.yml
Relates to: https://mozilla-hub.atlassian.net/browse/AMO-212
Add task and bug issue types with relevant labels applied. Allow specifying repository.
Docs for making issue templates/forms https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
I added these configurations to a test repo to verify what their effect is.
https://github.com/mozilla/addons/assets/19595165/29f2098c-bba9-45ad-b4b0-ba893f470148
https://github.com/mozilla/addons/assets/19595165/8d6fccfb-3d5b-4e42-ab4d-e7675c1f89fb
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO11-6)
=> Use issue types and forms

.github/workflows/transfer-issues.yml, scripts/transfer-issues.sh
Relates to: https://mozilla-hub.atlassian.net/browse/AMO-212
This pull request adds a workflow that can be used to transfer GitHub issues from one repository to another. The script uses the GitHub CLI tool to list all issues, sort them by creation date, and transfer them to a specified repository. This script can be useful when migrating repositories or consolidating multiple repositories into one.
We can specify the repository and number of issues to transfer. Alternatively you can specify a specific issue to transfer. There is only minimal validation currently but errors should be propagated and have been roughly tested if you give an issue that doesn't belong to the repo, or a repo that doesn't exist, or a count of 0.
It turns out to be easier to run this script on the addons repo …
=> Add workflow to transfer issues from another mozilla repository

.github/ISSUE_TEMPLATE/task-addons-frontend.yml, .github/ISSUE_TEMPLATE/task-addons-server.yml
As title.
As currently worded the template implies that for an issue to be ready to be worked on it must have an assignee already, which isn't always the case - we file issues as needed, but only assign them once we know who is working on them, and that it will happen in the next sprint or so.
I don't think this is possible to test before merging.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO11-44)
=> Update issue templates to not ask about an issue having an assignee to be ready

docs/server/push-duty.rst
We don't need to care about stage and -dev is gone. So we only make a git tag to deploy to prod. Hopefully this is clear enough..
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO2-46)
=> Update push duty docs for EW

.github/workflows/transfer-issues.yml, scripts/transfer-issues.sh
Allow filtering by state so we can transfer only open issues first.
When we run the migration we want to transfer the open issues first. THis let's us do that and continue with closed issues without needing further code changes.
You can test locally.
1. authenticate with github cli
```bash
gh login
```
2. Run a command to transfer an issue
```bash
FROM_NAME=addons-server STATES="[OPEN]" ./scripts/transfer-issues.sh
```
NOTE: this will actually transfer the issue. Wild west.
You can test the action in GHA by triggering [manually](https://github.com/mozilla/addons/actions/workflows/transfer-issues.yml)
Make sure to set the branch to `transfer-via-state` so it runs on this PR branch.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO2-60)
=> Allow filtering by issue state (open or closed or both)

.github/workflows/transfer-issues.yml
Forgot to map the input "states" to the environment variable "STATES" allowing the action to specify targeting open,closed, or both states.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO2-78)
=> Map states input to STATES environment variable to make state selection configurable from CLI

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/feature.yml, .github/ISSUE_TEMPLATE/task.yml, .github/PULL_REQUEST_TEMPLATE.md
fixes: mozilla/addons#15401
- Updated the bug report template to include a type field.
- Created a new feature request template with detailed fields for description and acceptance criteria.
- Added a task template for implementing portions of features with a description field.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1552)
=> Add new issue templates for bug reports, feature requests, and tasks

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature.yml, .github/PULL_REQUEST_TEMPLATE.md
fixes: mozilla/addons#15401
- Introduced a new pull request template to standardize submissions.
- Added a feature request template with fields for description and acceptance criteria.
- Updated the bug report template to include a type field.
- Enabled blank issues in the configuration for more flexibility.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1556)
=> Github template updates

.github/actions/slack/action.yml, .github/workflows/ci.yml
Fixes: mozilla/addons#15730
- Added logic to determine if a message should be sent based on the dry_run input in action.yml.
- Updated the CI workflow to include a job that tests the Slack action with various dry_run values, ensuring comprehensive coverage of scenarios.
The conditional for either sending the slack message or just printing what would be sent is somehow extremely difficult to get right.
We are now using bash to interpret the input and set an explicit value. Additionally we either send the message or print the message, not both.
=> Enhance Slack action with dry run functionality and update CI workflow
