mozilla/addons

- features/fxa-migration/README.md
How’s this @andymckay @mstriemer?
> FxA AMO Migration Specs

- docs/browser/index.rst
- docs/index.rst
- docs/repositories.rst
> add in repositories and browser page

- docs/server/push-duty.rst
> Document IRC bot and addons-frontend deployment

- docs/server/push-duty.rst
> Add docs re: project dependencies

- docs/conf.py
- docs/server/push-duty.rst
Fix #215
There are a myriad of different options for how to push the changes (cherry-picking, rebasing, merging from master first in the branch then back into master, etc) I picked the one I thought to be the simplest.
> Document how to push security fixes

- docs/conf.py
- docs/server/push-duty.rst
Fix push docs and remove @mstriemer from amo push duty.
> Remove mstriemer and update staging push documentation

- docs/index.rst
- docs/l10n.rst
> Docs for l10ners

- docs/server/push-duty.rst
This may not be official yet but let's even update the docs for a temporary experiment.
> Reflect our switch from etherpad to github

- docs/server/push-duty.rst
> Attempt to fix the Sphynx error

- default-github-labels.json
I used this file to create the standard labels for addons-blog:
```
npx github-labels -t <token> -f -c ./default-github-labels.json
```
> Add default github labels (JSON file)

- docs/server/push-duty.rst
> Add Extension Workshop to the push duty docs

- docs/server/push-duty.rst
Fixes #1574
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO11-5)
> Update docs about push duty & security fixes

- .github/workflows/transfer-issues.yml
- scripts/transfer-issues.sh
Fixes: #1753 
- Remove static values from environment variables (makes running the script locally easier with fewer vars to set)
- replace updateIssue with addLabeltoLabelable to preserve existing labels during transfer
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO2-13)
> Fixes and improvements to transfer-issues.yml/sh:

- scripts/transfer-issues.sh
Fixes: https://github.com/mozilla/addons/actions/runs/8844969108/job/24288005781
1. add error handling when executing the transfer issues action with a valid token that hasn't been saml authenticated for the "mozilla" org. Previously this would fail API requests, but the job would pass. We will rely on the job failling reliably so we should catch that error and exit the script.
2. Per advice from github support to help track and potentially filter issues that are included in the migraiton we can add a unique, static, label to the issues "migration:2024". This could be used to filter these issues afterwards or to filter email notifications to reduce spam in contributor inboxes.
3. The script is generating the repository:<name> label, but adding artificial "quotes" around it. Fixed that.
4. …
> Various mostly unrelated fixes we want to land before the mgiration.

- .github/workflows/transfer-issues.yml
- scripts/transfer-issues.sh
Parallel runs for different repos.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO2-499)
> Fix script

- .github/workflows/stale.yml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1152)
> Change stale period back to 180

- .readthedocs.yml
Fixes: mozilla/addons#15136
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1190)
> Install requirements file on RTD builds

- .github/workflows/docs.yml
Follow up: https://github.com/mozilla/addons/pull/15135
Relates to: mozilla/addons#15142
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1192)
> build docs with github pages

- .github/actions/context/action.yml
- .github/actions/login-docker/action.yml
- .github/actions/login-gar/action.yml
- .github/dependabot.yml
- .github/workflows/docs.yml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1217)
> Add reusable github actions

- .github/actions/slack/action.yml
- .github/workflows/push.yml
FIxes: mozilla/addons#15364
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1439)
> slack message
